version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "application"
      POSTGRES_USER: "application"
      POSTGRES_DB: "robotapp"
    ports:
      - 5432:5432
